--- # Configuration Port
server:
  port: 8081

--- # Configuration Thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

--- # Configuration Devtools
spring:
  devtools:
    livereload:
      enabled: true

--- # Configuration Postgresql
spring: 
  datasource:
    url: jdbc:postgresql://pschome.iptime.org:1033/boot
    username: iop2589
    password: qkqn1221

--- # Configuration mybatis
mybatis:
  mapper-locations: classpath:sqlmap/**/*.xml
  configuration:
    map-underscore-to-camel-case: true